server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
   config:
    server:
      encrypt.enabled: false
      git:
        uri: https://github.com/HarisDelalic/config-repo
        searchPaths: licenseservice
        username: native-cloud-apps
        password: 0ffended
